name: Continuos Integration

on:  
push:
    branches: ["main"]

jobs:
  continuos-integration:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Using Node.js
      uses: action/setup-node@v2
      with:
        node-version: 18.
    - name: run install
      run: |
      npm install
      npm run build
      npm run dev
    